### ISSUE TITLE
Ookii.Dialogs.Wpf.dll is not strong-name-signed

### ISSUE THREAD

**Issue by Kittyfisto** [caioproiete/ookii-dialogs-wpf#3]
I'd like to use your project in one of mine, however I'm currently unable to do so because the Ookii.Dialogs.Wpf.dll is not strong name signed.
My project requires strong-name-signing (unfortunately) and .NET requires that any SNS assembly only have dependencies to other SNS assemblies.

Would you consider publishing a signed nuget package?

**Comment by caioproiete** [comment]
@Kittyfisto Yes. I'll publish a new version of the nuget package with strong-name-signed assemblies in the next few days.

**Comment by caioproiete** [comment]
@Kittyfisto this is done: https://github.com/caioproiete/ookii-dialogs-wpf/releases/tag/v1.1.0

**Comment by Kittyfisto** [comment]
Many thanks for the quick fix, works like a charm!
